# Generated by Django 2.0.6 on 2018-06-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValuesCalculatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=64)),
                ('signal', models.CharField(max_length=64)),
                ('value', models.DateTimeField()),
                ('day', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValuesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=64)),
                ('signal', models.CharField(max_length=64)),
                ('value', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('acquisition', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
