# Generated by Django 2.0.6 on 2018-06-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20180618_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuescalculatedmodel',
            name='value',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='valuesmodel',
            name='value',
            field=models.CharField(max_length=10),
        ),
    ]
