# Generated by Django 2.0.6 on 2018-06-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20180618_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuescalculatedmodel',
            name='day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuescalculatedmodel',
            name='value',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuesmodel',
            name='acquisition',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuesmodel',
            name='value',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
