# Generated by Django 2.0.6 on 2018-06-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20180618_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuescalculatedmodel',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuesmodel',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
