# Generated by Django 2.0.6 on 2018-06-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20180618_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuescalculatedmodel',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
